### PR TITLE
Wafi Hossain - developer-exercise solution

### PR DESCRIPTION
**Pull request by 0wafi0**
### Instruction

- Ensure npm, node and typescript are installed globally
- npm install
- npm run build
- npm run start

### CODE REVIEW

**Comment by dinglidingli** [comment]
Thanks Wafi

**Comment by 0wafi0** [comment]
> 
> 
> Thanks Wafi

I've noticed a couple of mistakes there. am I able to quick;y make some changes there at all and make a second PR? 

Kind regards,
Wafi

**Comment by dinglidingli** [comment]
> > Thanks Wafi
> 
> I've noticed a couple of mistakes there. am I able to quick;y make some changes there at all and make a second PR?
> 
> Kind regards,
> Wafi

Don't worry Wafi, we are happy to talk about your thoughts during the interview.

**Comment by 0wafi0** [comment]
> 
> 
> > > Thanks Wafi
> > 
> > 
> > I've noticed a couple of mistakes there. am I able to quick;y make some changes there at all and make a second PR?
> > Kind regards,
> > Wafi
> 
> Don't worry Wafi, we are happy to talk about your thoughts during the interview.

No worries, I've just made some quick changes just in case, I've calculated a couple of things incorrectly. See you at the interview.

**Pull request closed without merging**
